import { useState, useEffect } from "react";
import { Link } from "react-router-dom";
import { useTranslation } from "react-i18next";
import DashboardLayout from "@/components/layout/DashboardLayout";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Switch } from "@/components/ui/switch";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { MoreVertical, Plus, Loader2, Flag, Archive, ChevronRight } from "lucide-react";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from "@/components/ui/alert-dialog";
import { useFlagStore } from "@/store/flagStore";
import { useProjectStore } from "@/store/projectStore";
import { toCamelCase } from "@/lib/string-utils";
import { cn } from "@/lib/utils";
import type { FeatureFlag } from "@/types";

export default function FlagsPage() {
  const { t } = useTranslation();
  const { selectedProject } = useProjectStore();
  const { flags, loading, fetchFlags, createFlag, toggleFlag, archiveFlag } = useFlagStore();

  const [togglingFlags, setTogglingFlags] = useState<Set<string>>(new Set());
  const [selectedFlag, setSelectedFlag] = useState<FeatureFlag | null>(null);
  const [isCreateDialogOpen, setIsCreateDialogOpen] = useState(false);
  const [isCreating, setIsCreating] = useState(false);
  const [newFlag, setNewFlag] = useState({ name: "", key: "", description: "" });
  const [flagToArchive, setFlagToArchive] = useState<FeatureFlag | null>(null);

  useEffect(() => {
    if (selectedProject) fetchFlags(selectedProject.id);
  }, [selectedProject, fetchFlags]);

  const handleNameChange = (name: string) =>
    setNewFlag({ ...newFlag, name, key: toCamelCase(name) });

  const handleCreateFlag = async () => {
    if (!newFlag.name || !newFlag.key || !selectedProject) return;
    setIsCreating(true);
    try {
      await createFlag(selectedProject.id, {
        name: newFlag.name,
        key: newFlag.key,
        description: newFlag.description || undefined,
        type: "boolean",
        defaultValue: "false",
      });
      setIsCreateDialogOpen(false);
      setNewFlag({ name: "", key: "", description: "" });
    } catch {
      alert(t("flags.createError"));
    } finally {
      setIsCreating(false);
    }
  };

  const handleToggleFlag = async (flagId: string, environmentId: string, currentState: boolean) => {
    const key = `${flagId}-${environmentId}`;
    setTogglingFlags((prev) => new Set(prev).add(key));
    try {
      await toggleFlag(flagId, environmentId, currentState);
    } finally {
      setTogglingFlags((prev) => {
        const s = new Set(prev);
        s.delete(key);
        return s;
      });
    }
  };

  const confirmArchiveFlag = async () => {
    if (!flagToArchive) return;
    try {
      await archiveFlag(flagToArchive.id);
      setFlagToArchive(null);
    } catch (e) {
      console.error(e);
    }
  };

  if (loading && !flags.length) {
    return (
      <DashboardLayout>
        <div className="flex h-96 items-center justify-center">
          <Loader2 className="text-muted-foreground h-8 w-8 animate-spin" />
        </div>
      </DashboardLayout>
    );
  }

  const CreateFlagDialog = (
    <Dialog open={isCreateDialogOpen} onOpenChange={setIsCreateDialogOpen}>
      <DialogTrigger asChild>
        <Button size="sm" className="w-full sm:w-auto">
          <Plus className="mr-2 h-4 w-4" />
          {t("flags.newFlag")}
        </Button>
      </DialogTrigger>
      <DialogContent>
        <DialogHeader>
          <DialogTitle>{t("flags.createFlag")}</DialogTitle>
          <DialogDescription>{t("flags.createDesc")}</DialogDescription>
        </DialogHeader>
        <div className="grid gap-4 py-4">
          <div className="grid gap-2">
            <Label htmlFor="flag-name">{t("flags.flagName")}</Label>
            <Input
              id="flag-name"
              placeholder={t("flags.namePlaceholder")}
              value={newFlag.name}
              onChange={(e) => handleNameChange(e.target.value)}
            />
          </div>
          <div className="grid gap-2">
            <Label htmlFor="flag-key">{t("flags.flagKey")}</Label>
            <Input id="flag-key" value={newFlag.key} disabled className="bg-muted font-mono" />
            <p className="text-muted-foreground text-xs">{t("flags.keyAutoGenerated")}</p>
          </div>
          <div className="grid gap-2">
            <Label htmlFor="flag-desc">{t("flags.description")}</Label>
            <Input
              id="flag-desc"
              placeholder={t("flags.descriptionPlaceholder")}
              value={newFlag.description}
              onChange={(e) => setNewFlag({ ...newFlag, description: e.target.value })}
            />
          </div>
        </div>
        <DialogFooter className="gap-2 sm:gap-0">
          <Button variant="outline" onClick={() => setIsCreateDialogOpen(false)}>
            {t("common.cancel")}
          </Button>
          <Button onClick={handleCreateFlag} disabled={!newFlag.name || !newFlag.key || isCreating}>
            <Loader2 className={cn("h-4 w-4 animate-spin", !isCreating && "invisible")} />
            {isCreating ? t("common.creating") : t("flags.createFlag")}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );

  return (
    <DashboardLayout>
      <div className="flex flex-col gap-4 p-4 sm:gap-6 sm:p-6">
        {/* Header */}
        <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
          <div>
            <h1 className="text-2xl font-bold tracking-tight sm:text-3xl">{t("flags.title")}</h1>
            <p className="text-muted-foreground mt-1 text-sm">{t("flags.subtitle")}</p>
          </div>
          <div className="hidden items-center gap-2 sm:flex">
            <Button variant="outline" size="sm" asChild>
              <Link to="/dashboard/flags/archived">
                <Archive className="mr-2 h-4 w-4" />
                {t("flags.viewArchived")}
              </Link>
            </Button>
            {CreateFlagDialog}
          </div>
        </div>

        {/* ── MOBILE: card list (hidden sm+) ── */}
        <div className="flex flex-col gap-3 sm:hidden">
          {/* Mobile action bar */}
          <div className="flex flex-col gap-2">
            <div className="w-full">{CreateFlagDialog}</div>
            <Button variant="outline" size="sm" className="w-full" asChild>
              <Link to="/dashboard/flags/archived">
                <Archive className="mr-2 h-4 w-4" />
                {t("flags.viewArchived")}
              </Link>
            </Button>
          </div>

          {flags.length === 0 ? (
            <div className="flex flex-col items-center gap-3 py-16 text-center">
              <Flag className="text-muted-foreground h-14 w-14" />
              <h3 className="font-semibold">{t("flags.noFlags")}</h3>
              <p className="text-muted-foreground max-w-xs text-sm">{t("flags.noFlagsDesc")}</p>
            </div>
          ) : (
            flags.map((flag) => {
              const ps = flag.flagStates?.find((s) => s.environment.key === "production");
              const isEnabled = ps?.isEnabled || false;
              const toggleKey = `${flag.id}-${ps?.environmentId}`;
              return (
                <button
                  key={flag.id}
                  type="button"
                  onClick={() => setSelectedFlag(flag)}
                  className={cn(
                    "bg-card border-border flex w-full items-center gap-3 rounded-lg border p-4 text-left shadow-sm",
                    "active:bg-muted transition-colors",
                  )}
                >
                  <div
                    className={cn(
                      "flex h-9 w-9 shrink-0 items-center justify-center rounded-full",
                      isEnabled ? "bg-primary/10" : "bg-muted",
                    )}
                  >
                    <Flag
                      className={cn("h-4 w-4", isEnabled ? "text-primary" : "text-muted-foreground")}
                    />
                  </div>
                  <div className="min-w-0 flex-1">
                    <p className="truncate font-medium">{flag.name}</p>
                    <p className="text-muted-foreground truncate font-mono text-xs">{flag.key}</p>
                  </div>
                  <div className="flex shrink-0 items-center gap-2">
                    <Switch
                      checked={isEnabled}
                      disabled={togglingFlags.has(toggleKey)}
                      onCheckedChange={(checked) => {
                        // prevent card click
                        if (ps) handleToggleFlag(flag.id, ps.environmentId, !checked);
                      }}
                      onClick={(e) => e.stopPropagation()}
                    />
                    <Loader2
                      className={cn(
                        "text-muted-foreground h-3.5 w-3.5 animate-spin",
                        !togglingFlags.has(toggleKey) && "invisible",
                      )}
                    />
                    <ChevronRight className="text-muted-foreground h-4 w-4" />
                  </div>
                </button>
              );
            })
          )}
        </div>

        {/* ── DESKTOP: table (hidden below sm) ── */}
        {flags.length === 0 ? (
          <div className="hidden rounded-lg border p-12 text-center sm:block">
            <Flag className="text-muted-foreground mx-auto mb-4 h-16 w-16" />
            <h3 className="mb-2 text-lg font-semibold">{t("flags.noFlags")}</h3>
            <p className="text-muted-foreground mx-auto mb-4 max-w-md">{t("flags.noFlagsDesc")}</p>
            <Button onClick={() => setIsCreateDialogOpen(true)}>
              <Plus className="mr-2 h-4 w-4" />
              {t("flags.createFirst")}
            </Button>
          </div>
        ) : (
          <div className="border-border bg-card hidden rounded-lg border shadow-sm sm:block">
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>{t("flags.name")}</TableHead>
                  <TableHead>{t("flags.key")}</TableHead>
                  <TableHead>{t("flags.type")}</TableHead>
                  <TableHead className="w-[160px]">{t("flags.status")}</TableHead>
                  <TableHead className="text-right">{t("common.actions")}</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {flags.map((flag) => {
                  const ps = flag.flagStates?.find((s) => s.environment.key === "production");
                  const isEnabled = ps?.isEnabled || false;
                  const toggleKey = `${flag.id}-${ps?.environmentId}`;
                  return (
                    <TableRow key={flag.id}>
                      <TableCell className="font-medium">
                        <Link to={`/dashboard/flags/${flag.id}`} className="hover:underline">
                          {flag.name}
                        </Link>
                      </TableCell>
                      <TableCell className="text-muted-foreground font-mono text-sm">
                        {flag.key}
                      </TableCell>
                      <TableCell>
                        <Badge variant="secondary">{flag.type}</Badge>
                      </TableCell>
                      <TableCell className="w-[160px]">
                        <div className="flex items-center gap-2.5">
                          <Switch
                            checked={isEnabled}
                            disabled={togglingFlags.has(toggleKey)}
                            onCheckedChange={() =>
                              ps && handleToggleFlag(flag.id, ps.environmentId, isEnabled)
                            }
                          />
                          <span
                            className={cn(
                              "inline-block min-w-[2.5rem] text-sm font-medium",
                              isEnabled ? "text-primary" : "text-muted-foreground",
                            )}
                          >
                            {isEnabled ? t("flags.enabled") : t("flags.disabled")}
                          </span>
                          <Loader2
                            className={cn(
                              "text-muted-foreground h-3.5 w-3.5 animate-spin",
                              !togglingFlags.has(toggleKey) && "invisible",
                            )}
                          />
                        </div>
                      </TableCell>
                      <TableCell className="text-right">
                        <DropdownMenu>
                          <DropdownMenuTrigger asChild>
                            <Button variant="ghost" size="icon">
                              <MoreVertical className="h-4 w-4" />
                            </Button>
                          </DropdownMenuTrigger>
                          <DropdownMenuContent align="end">
                            <DropdownMenuItem asChild>
                              <Link to={`/dashboard/flags/${flag.id}`}>
                                {t("common.viewDetails")}
                              </Link>
                            </DropdownMenuItem>
                            <DropdownMenuItem
                              className="text-destructive"
                              onClick={() => setFlagToArchive(flag)}
                            >
                              {t("flags.archive")}
                            </DropdownMenuItem>
                          </DropdownMenuContent>
                        </DropdownMenu>
                      </TableCell>
                    </TableRow>
                  );
                })}
              </TableBody>
            </Table>
          </div>
        )}

      </div>

      {/* Archive confirm */}
      <AlertDialog
        open={!!flagToArchive}
        onOpenChange={(open) => { if (!open) setFlagToArchive(null); }}
      >
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>{t("flags.archiveConfirm")}</AlertDialogTitle>
            <AlertDialogDescription>{t("flags.archiveWarning")}</AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel>{t("common.cancel")}</AlertDialogCancel>
            <AlertDialogAction variant="destructive" onClick={confirmArchiveFlag}>
              {t("flags.archiveAction")}
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>

      {/* Mobile flag detail dialog */}
      <Dialog open={!!selectedFlag} onOpenChange={(open) => !open && setSelectedFlag(null)}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2">
              <Flag className="text-muted-foreground h-5 w-5" />
              {selectedFlag?.name}
            </DialogTitle>
            <DialogDescription>
              <code className="bg-muted rounded px-1.5 py-0.5 font-mono text-xs">
                {selectedFlag?.key}
              </code>
            </DialogDescription>
          </DialogHeader>
          {selectedFlag && (() => {
            const ps = selectedFlag.flagStates?.find((s) => s.environment.key === "production");
            const enabled = ps?.isEnabled || false;
            const tKey = `${selectedFlag.id}-${ps?.environmentId}`;
            return (
              <div className="space-y-4 py-1">
                <div className="flex items-center justify-between border-b pb-4">
                  <span className="text-muted-foreground text-sm">{t("flags.type")}</span>
                  <Badge variant="secondary">{selectedFlag.type}</Badge>
                </div>
                <div className="flex items-center justify-between">
                  <span className="text-sm font-medium">
                    {t("flags.status")} — Production
                  </span>
                  <div className="flex items-center gap-2">
                    <Switch
                      checked={enabled}
                      disabled={togglingFlags.has(tKey)}
                      onCheckedChange={() =>
                        ps && handleToggleFlag(selectedFlag.id, ps.environmentId, enabled)
                      }
                    />
                    <span className={cn("text-sm font-medium", enabled ? "text-primary" : "text-muted-foreground")}>
                      {enabled ? t("flags.enabled") : t("flags.disabled")}
                    </span>
                    <Loader2
                      className={cn(
                        "text-muted-foreground h-3.5 w-3.5 animate-spin",
                        !togglingFlags.has(tKey) && "invisible",
                      )}
                    />
                  </div>
                </div>
              </div>
            );
          })()}
          <DialogFooter className="flex-col gap-2">
            <Button className="w-full" asChild onClick={() => setSelectedFlag(null)}>
              <Link to={`/dashboard/flags/${selectedFlag?.id}`}>{t("common.viewDetails")}</Link>
            </Button>
            <Button
              variant="outline"
              className="w-full text-destructive hover:text-destructive"
              onClick={() => {
                setFlagToArchive(selectedFlag);
                setSelectedFlag(null);
              }}
            >
              <Archive className="mr-2 h-4 w-4" />
              {t("flags.archive")}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </DashboardLayout>
  );
}
